# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [2]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [3]:
# Load the full dataset
with open("..\\..\\..\\data\\wine-reviews\\winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [4]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [5]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [6]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [7]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [8]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [9]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [10]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [11]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [12]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [13]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [14]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [15]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [16]:
len(text_ds)

4060

In [17]:
example_input_output = train_ds.take(1).get_single_element()

In [18]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   20,    2,   29,    2,  100,    2,    8,  226,
         94,    5,  650,    3,   11,   72,   36,    3,   86,  613,    5,
        300,   16, 1112,   11,   73,   30,    4,   35,   66,    4,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int64)>

In [19]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,   20,    2,   29,    2,  100,    2,    8,  226,   94,
          5,  650,    3,   11,   72,   36,    3,   86,  613,    5,  300,
         16, 1112,   11,   73,   30,    4,   35,   66,    4,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int64)>

## 5. Create the causal attention mask function <a name="causal"></a>

In [20]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
i = tf.range(10)[:, None]
j = tf.range(10)
m = i >= j

In [28]:
i.numpy(), j.numpy(), tf.cast(m, tf.int32).numpy().T

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]))

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [29]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [30]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [31]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [32]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddin  (None, None, 256)        2580480   
 g (TokenAndPositionEmbeddin                                     
 g)                                                              
                                                                 
 transformer_block (Transfor  ((None, None, 256),      658688    
 merBlock)                    (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5,809,168
Trainable params: 5,809,168
Non-trainable params: 0
___________________________________________________

In [33]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [34]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [35]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [36]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4055/4060 [============================>.] - ETA: 0s - loss: 2.2508 - dense_2_loss: 2.2508
generated text:
wine review : us : california : chardonnay : a bit too angular for drinking now with sweet fruit and lots of spicy toast , mango and vanilla flavors . has punchy flavors recommend . 

4060/4060 [==============================] - 30s 7ms/step - loss: 2.2504 - dense_2_loss: 2.2504
Epoch 2/5
4058/4060 [============================>.] - ETA: 0s - loss: 1.9590 - dense_2_loss: 1.9590
generated text:
wine review : france : france other : tannat : acidity gives a rich edge of berry - flavored tannins this single - vineyard wine . this is finely textured and ripe while certainly contrasts with the ripe red fruits . with its dry core , the wine is ready to drink . 

4060/4060 [==============================] - 28s 7ms/step - loss: 1.9592 - dense_2_loss: 1.9592
Epoch 3/5
4060/4060 [==============================] - ETA: 0s - loss: 1.8895 - dense_2_loss: 1.8895
generated text:
wine 

In [37]:
# Save the final model
gpt.save("./models/gpt")

INFO:tensorflow:Assets written to: ./models/gpt\assets


INFO:tensorflow:Assets written to: ./models/gpt\assets


# 3. Generate text using the Transformer

In [38]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [39]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : california : pinot gris : an immaculate structure surrounds mouthwatering and the wine , [UNK] past years , with deliciously ripe candied flavors which have a creamy texture . oaky , it has honeyed richness that soothes the palate all given the vineyard sites in this virginia roussanne . it delivers a lovely wood element . 



In [40]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : veneto : glera : made with organically cultivated garganega , this opens with a fragrance of yellow flower , hay and a whiff of exotic spice . the palate has a soft , creamy mouthfeel , creamy and soft acidity . 



In [41]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : a light , delicate style of riesling , with a shower of lemon - lime acidity , mineral , dried herb and mineral tones . it ' s a bit lean , but the finish is brisk , with sour lemon acidity . 



::   	100.0%
grosso:   	0.0%
-:   	0.0%
zealand:   	0.0%
.:   	0.0%
--------



mosel:   	96.09%
pfalz:   	1.97%
rheingau:   	1.28%
rheinhessen:   	0.49%
nahe:   	0.11%
--------



::   	98.34%
-:   	1.66%
valley:   	0.0%
blanc:   	0.0%
du:   	0.0%
--------



riesling:   	100.0%
pinot:   	0.0%
sparkling:   	0.0%
white:   	0.0%
spätburgunder:   	0.0%
--------



::   	100.0%
-:   	0.0%
grosso:   	0.0%
blanc:   	0.0%
du:   	0.0%
--------



whiffs:   	39.53%
a:   	13.85%
while:   	8.85%
this:   	5.56%
zesty:   	3.17%
--------



whiff:   	35.88%
touch:   	11.96%
crush:   	8.81%
delicate:   	4.39%
savory:   	4.26%
--------



,:   	74.21%
-:   	9.77%
touch:   	9.08%
mineral:   	2.92%
whiff:   	0.87%
--------



delicate:   	59.66%
lacy:   	5.89%
elegant:   	5.58%
fruity:   	3.65%
bright:   	3.24%
--------



riesling:   	42.72%
perfume:   	16.57%
wine:   	7.04%
style:   	6.19%
,:   	5.37%
--------



of:   	98.05%
,:   	1.55%
riesling:   	0.32%
and:   	0.02%
that:   	0.02%
--------



riesling:   	99.68%
white:   	0.11%
wine:   	0.06%
kabinett:   	0.05%
sweet:   	0.01%
--------



,:   	98.43%
and:   	1.07%
that:   	0.31%
with:   	0.05%
.:   	0.04%
--------



with:   	54.77%
this:   	37.12%
but:   	2.96%
yet:   	1.48%
it:   	0.9%
--------



a:   	74.17%
delicate:   	8.16%
hints:   	1.82%
notes:   	1.67%
an:   	1.23%
--------



delicate:   	35.14%
touch:   	17.2%
hint:   	14.19%
whiff:   	11.19%
mineral:   	4.2%
--------



of:   	100.0%
that:   	0.0%
like:   	0.0%
and:   	0.0%
-:   	0.0%
--------



lemon:   	34.81%
citrus:   	14.11%
fresh:   	7.74%
slate:   	6.86%
lime:   	6.46%
--------



-:   	43.06%
and:   	31.71%
,:   	22.06%
zest:   	0.98%
blossoms:   	0.74%
--------



lime:   	99.95%
honey:   	0.02%
blossom:   	0.01%
grapefruit:   	0.0%
marmalade:   	0.0%
--------



acidity:   	95.27%
and:   	3.18%
,:   	0.61%
zest:   	0.42%
flavor:   	0.11%
--------



and:   	64.53%
,:   	32.14%
that:   	1.34%
.:   	1.16%
on:   	0.34%
--------



green:   	21.93%
honey:   	14.29%
tangerine:   	11.9%
lime:   	7.76%
grapefruit:   	7.09%
--------



and:   	69.55%
,:   	30.43%
-:   	0.01%
oil:   	0.0%
tones:   	0.0%
--------



slate:   	84.63%
honey:   	3.79%
mineral:   	2.72%
lime:   	1.89%
wet:   	1.25%
--------



herb:   	87.81%
herbs:   	5.88%
apple:   	2.08%
-:   	1.41%
stone:   	0.45%
--------



and:   	89.71%
,:   	10.29%
-:   	0.0%
tea:   	0.0%
pollen:   	0.0%
--------



mineral:   	34.66%
slate:   	22.83%
spice:   	16.29%
honey:   	6.82%
lime:   	3.91%
--------



tones:   	38.0%
flavors:   	31.16%
notes:   	23.09%
,:   	2.41%
.:   	1.57%
--------



.:   	23.23%
on:   	20.36%
extend:   	19.5%
,:   	18.77%
are:   	3.25%
--------



it:   	86.99%
the:   	6.86%
a:   	2.4%
this:   	1.23%
:   	0.59%
--------



':   	99.99%
finishes:   	0.01%
is:   	0.0%
drinks:   	0.0%
has:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
riesling:   	0.0%
off:   	0.0%
--------



a:   	51.44%
dry:   	18.42%
brisk:   	4.22%
delicate:   	3.26%
delicately:   	1.74%
--------



bit:   	50.14%
straightforward:   	13.13%
deeply:   	5.13%
delightfully:   	4.74%
very:   	3.09%
--------



lean:   	61.17%
austere:   	27.28%
demure:   	1.55%
on:   	0.72%
softer:   	0.61%
--------



,:   	48.4%
in:   	40.01%
and:   	5.63%
on:   	5.37%
but:   	0.45%
--------



but:   	88.78%
with:   	6.42%
yet:   	3.93%
offering:   	0.25%
finishing:   	0.05%
--------



the:   	37.33%
it:   	13.45%
a:   	9.49%
not:   	7.79%
still:   	3.82%
--------



finish:   	69.42%
palate:   	19.58%
wine:   	6.49%
overall:   	1.13%
flavors:   	0.93%
--------



is:   	97.55%
lingers:   	1.09%
shows:   	0.37%
has:   	0.35%
does:   	0.13%
--------



dry:   	31.34%
brisk:   	29.67%
long:   	15.23%
marked:   	4.21%
lean:   	2.58%
--------



and:   	85.38%
,:   	7.81%
.:   	6.08%
with:   	0.62%
in:   	0.07%
--------



with:   	78.45%
but:   	6.89%
clean:   	5.47%
and:   	2.75%
suggesting:   	1.22%
--------



a:   	94.77%
acidity:   	0.82%
bracing:   	0.66%
an:   	0.49%
zesty:   	0.42%
--------



lime:   	36.18%
lemon:   	26.02%
tangerine:   	8.99%
-:   	6.16%
orange:   	6.08%
--------



and:   	78.64%
acidity:   	6.86%
,:   	6.59%
-:   	6.19%
zest:   	0.75%
--------



.:   	62.63%
and:   	36.32%
that:   	0.85%
,:   	0.16%
to:   	0.01%
--------



:   	98.59%
drink:   	1.1%
it:   	0.21%
a:   	0.06%
the:   	0.02%
--------

